"use client"

import { DashboardShell } from "@/components/dashboard-shell"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, FileText, Calendar, Filter } from "lucide-react"

export default function ReportsPage() {
  const reports = [
    { title: "Monthly Performance Audit", type: "PDF", date: "Feb 01, 2026", size: "2.4 MB" },
    { title: "Institutional Growth Report", type: "XLSX", date: "Jan 15, 2026", size: "1.1 MB" },
    { title: "Skill Gap Analysis - Q4 2025", type: "PDF", date: "Jan 05, 2026", size: "4.8 MB" },
    { title: "Platform Integrity Log", type: "CSV", date: "Jan 01, 2026", size: "850 KB" },
    { title: "Global Hiring Trends 2025", type: "PDF", date: "Dec 20, 2025", size: "12.2 MB" },
  ]

  return (
    <DashboardShell>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">System Reports</h1>
            <p className="text-muted-foreground">Access and export platform-wide data and audit logs.</p>
          </div>
          <Button className="gap-2">
            <Filter className="h-4 w-4" />
            Generate Custom Report
          </Button>
        </div>

        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Recent Reports</CardTitle>
              <CardDescription>Scheduled and on-demand reports generated by the system.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {reports.map((report, i) => (
                  <div
                    key={i}
                    className="flex items-center justify-between p-4 rounded-lg border border-border/50 hover:bg-muted/30 transition-colors"
                  >
                    <div className="flex items-center gap-4">
                      <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <FileText className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <p className="font-semibold">{report.title}</p>
                        <div className="flex items-center gap-3 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Calendar className="h-3 w-3" />
                            {report.date}
                          </span>
                          <span>{report.type}</span>
                          <span>{report.size}</span>
                        </div>
                      </div>
                    </div>
                    <Button variant="outline" size="sm" className="gap-2 bg-transparent">
                      <Download className="h-4 w-4" />
                      Download
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardShell>
  )
}
